# Generated by Django 3.1.8 on 2021-06-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alter', models.CharField(max_length=50)),
                ('primary_power', models.CharField(max_length=100)),
                ('secondary_power', models.CharField(max_length=100)),
                ('catchphrase', models.TextField()),
            ],
        ),
    ]
